version: '3.8'

services:
  oleg-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Telegram Configuration
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET:-}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
      
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      
      # Bot Behavior Settings
      - WINDOW_SIZE=${WINDOW_SIZE:-50}
      - REPLY_TARGET_RATIO=${REPLY_TARGET_RATIO:-0.10}
      - GAP_MIN_SECONDS=${GAP_MIN_SECONDS:-20}
      - MAX_RESPONSE_WORDS=${MAX_RESPONSE_WORDS:-100}
      
      # Server Configuration
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - DEBUG=${DEBUG:-false}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - oleg-bot
    restart: unless-stopped
    profiles:
      - production